global:
  name: fast-api

autoscaling:
  enabled: false
  props: {}

nodeSelector:
  enabled: false
  props: {}

replicaCount: 2

image:
  repository: notSet
  tag: notSet


secret:
  HASURA_URL: "http://34.117.253.53/v1/graphql"
  HASURA_TOKEN: "cWgU,%'u)%tcU4,%"


env:
  ENV: "dev"