global:
  name: fast-api

autoscaling:
  enabled: false
  props: {}

nodeSelector:
  enabled: false
  props: {}

replicaCount: 2

image:
  repository: notSet
  tag: notSet


secret:
  HASURA_URL: ""
  HASURA_TOKEN: ""


env:
  ENV: "dev"
