apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: { { .Values.global.name } }
        version: "{{ .Values.image.tag }}"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Values.global.name }}
        ports:
          - containerPort: 80
        env:
        {{- range $k, $v := .Values.env }}
          - name: {{ $k }}
            value: {{ $v | quote }}
        {{- end }}
        {{- range $k, $v := .Values.secret }}
          - name: {{ $k }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.global.name }}
                key: {{ $k }}
        {{- end }}
