apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
        version: "{{ .Values.image.tag }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Values.global.name }}
          env:
          {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          {{- range $k, $v := .Values.secret }}
            - name: { { $k } }
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.name }}
                  key: {{ $k }}
          {{- end }}
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: fastapilogin # 1. docker login 2.kubectl create secret docker-registry fastapilogin --namespace=pod_namespace_name --from-file=.dockerconfigjson=/home/sipan/.docker/config.json