apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.global.name }}
  ports:
    - port: 8000
      targetPort: 80
      name: http-action-server-sidecar