name: Hs ml

on:
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with blake
      run: |
        black . --check
        isort . -c --profile black
        
  test:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: 3.9
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: poetry install --no-interaction
        
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          poetry run pytest -x -vvv --pdb
          poetry run pytest --cov-report term --cov-fail-under=90
