apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.global.name }}-virtualservice
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.vService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  http:
    - route:
      - destination:
          host: {{ .Values.global.name }}-service
          port:
            number: 5000