apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.global.name }}-worker"
  namespace: {{ .Release.Namespace }}
data:
  {{- range $k, $v := .Values.worker.secret }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
